<a href="https://colab.research.google.com/github/ijyoj/projects/blob/main/restaurant_reviews_NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np





In [ ]:
path='/content/drive/MyDrive/Colab Notebooks/Restaurant_Reviews (1).tsv'
df=pd.read_csv(path,delimiter='\t')
df.head()

Review  Liked
0                           Wow... Loved this place.      1
1                                 Crust is not good.      0
2          Not tasty and the texture was just nasty.      0
3  Stopped by during the late May bank holiday of...      1
4  The selection on the menu was great and so wer...      1

In [ ]:
#Text preprocessing
#importing all required modules
import re
import nltk
from nltk.stem.porter import PorterStemmer
from nltk.corpus import stopwords
nltk.download('stopwords')
from sklearn.feature_extraction.text import CountVectorizer
for i in range(5):
  print(df['Review'][i])
df.iloc[0:1,0:1].values



Wow... Loved this place.
Crust is not good.
Not tasty and the texture was just nasty.
Stopped by during the late May bank holiday off Rick Steve recommendation and loved it.
The selection on the menu was great and so were the prices.


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


array([['Wow... Loved this place.']], dtype=object)

In [ ]:
#first we remove all other special characters using regular expression.
#next convert it into lower case
#split into words
#stemming of the words
#convert them as a string
#we append to the list in which each element is one row of data
ps=PorterStemmer()
cv=CountVectorizer()
corpus=[]
for i in range(1000):
  pattern=r'[^a-zA-Z]'
  review=re.sub(pattern, " ", df['Review'][i])
  review=review.lower()
  review=review.split()
  review=[ps.stem(word) for word in review if word not in stopwords.words('english')]
  review=' '.join(review)
  corpus.append(review)
print(corpus[0:5])
X=cv.fit_transform(corpus[0:5]).toarray()
X



['wow love place', 'crust good', 'tasti textur nasti', 'stop late may bank holiday rick steve recommend love', 'select menu great price']


array([[0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0],
       [1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0]])

In [ ]:
X=cv.fit_transform(corpus).toarray()
print(X)
Y=df.iloc[:,1].values




[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,random_state=2)
len(y_test)


200

In [ ]:
#Randomforest classifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix,accuracy_score
rd=RandomForestClassifier(n_estimators=500,criterion='entropy')
rd.fit(x_train,y_train)
y_predict=rd.predict(x_test)
print('Confusion Matrix:')
print(confusion_matrix(y_predict,y_test))
print('*'*50)
print('Accuracy Score:')
accuracy_score(y_predict,y_test)

Confusion Matrix:
[[95 36]
 [13 56]]
**************************************************
Accuracy Score:


0.755